PSR-18 HTTP 客户端实现
botuniverse/php-libonebot pull request #28
Opened 2022-01-02 10:33 UTC by crazywhalecc

目前已实现客户端：

- [X] Swoole 协程客户端
- [X] Stream 流
- [ ] Curl
- [ ] Workerman 异步客户端

2022-01-02 10:37 UTC, crazywhalecc commented
Swoole 测试代码：

```php
go(function () {
    $request = \OneBot\Http\HttpFactory::getInstance()->createRequest('GET', 'http://captive.apple.com/', ['X-Asd' => 'asdasd']);
    $client = new \OneBot\Http\Client\SwooleClient(['timeout' => 2]);
    $response = $client->sendRequest($request);
    echo $response->getBody() . PHP_EOL;
});

\Swoole\Event::wait();
```

Stream 测试代码：

```php
$request = \OneBot\Http\HttpFactory::getInstance()->createRequest('GET', 'https://example.com/', ['X-Asd' => 'asdasd']);
$client = new \OneBot\Http\Client\StreamClient();
$response = $client->sendRequest($request);
echo $response->getBody().PHP_EOL;
```

2022-01-02 11:30 UTC, crazywhalecc commented
题外话：客户端的东西写好是真的多，感觉这么一套写完，就已经是一个框架了。

2022-01-02 11:38 UTC, sunxyw commented
那么，是否有直接引入第三方 HTTP 库的可能呢 🤔 
毕竟完整实现一个 HTTP 客户端需要很大工作量和精力。

2022-01-02 11:39 UTC, crazywhalecc commented
> 那么，是否有直接引入第三方 HTTP 库的可能呢 🤔 毕竟完整实现一个 HTTP 客户端需要很大工作量和精力。

现在已经完整实现了（

2022-01-02 11:41 UTC, crazywhalecc commented
之前考虑过引入 nyholm 和 Guzzle，但是考虑到还有可能此库对逻辑端同样适用，且避免过度依赖，对于基础的通信方式有一个最基本的实现应该就足够了。比如目前 StreamClient 和 SwooleClient 仅做了最基本的 HTTP 请求实现，剩余的花哨玩法也可以通过暴露上级对象来自行实现。

2022-01-02 12:29 UTC, crazywhalecc commented
Swoole WebSocket 客户端测试代码：

```php
go(function () {
    $client = \OneBot\V12\Driver\Swoole\WebSocketClient::createFromAddress('ws://127.0.0.1:9502');
    $client->setMessageCallback(function ($frame, $client) {
        echo "received message: {$frame->data}\n";
        sleep(2);
        $client->push(json_encode(['hello', 'server']));
    });
    $client->setCloseCallback(function () {
        echo "Closed\n";
    });
    $client->create();
    sleep(2);
    $client->push('hello');

});
\Swoole\Event::wait();
```

2022-01-02 12:34 UTC, crazywhalecc commented
@sunxyw 目前你觉得 WebSocket 客户端方案是否可行？接下来的工作就剩 Workerman 使用 TcpAsyncConnection 来实现一个同接口 `WebSocketClientInterface` 的客户端了。

接口趁现在还没做完，有需要调整的地方可以尽快调整一下。

2022-01-05 16:35 UTC, crazywhalecc commented
根据实际实现情况来看，打算放弃实现 Workerman 的 HTTP 异步客户端，因为看了下源码它是纯异步写的，没有同步的兼容部分，且需要用户自行 require 这个库才能使用。在 OneBot 实现中可以默认使用 Curl 或 Stream，Swoole 驱动下默认使用 Swoole。

2022-01-05 16:36 UTC, crazywhalecc commented
CurlClient 测试代码：

```php
$client = new \OneBot\Http\Client\CurlClient();
$request = \OneBot\Http\HttpFactory::getInstance()->createRequest('GET', 'http://127.0.0.1:9002/index.html');
$response = $client->sendRequest($request);
ob_dump($response->getBody()->getContents());
```

2022-01-07 06:36 UTC, crazywhalecc commented
Workerman WebSocket 客户端测试代码：

```php
$worker = new \OneBot\V12\Driver\Workerman\Worker();
$worker->onWorkerStart = function () {
    $client = new \OneBot\V12\Driver\Workerman\WebSocketClient();
    $request = \OneBot\Http\HttpFactory::getInstance()->createRequest('GET', 'ws://127.0.0.1:9502');
    $client->withRequest($request);
    $client->setMessageCallback(function ($message) {
    });
    $client->connect();
};
\OneBot\V12\Driver\Workerman\Worker::runAll();
```

2022-01-07 10:39 UTC, sunxyw commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +        ob_dump($this->request->getUri());
遗漏了测试代码？

2022-01-07 10:48 UTC, crazywhalecc commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +        ob_dump($this->request->getUri());
已删除

2022-01-07 11:05 UTC, sunxyw requested changes

2022-01-07 11:05 UTC, sunxyw commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +        if (!$this->status != self::STATUS_INITIAL) {
`!` 和 `!=` 重复了，会导致 `STATUS_INITIAL` 时无法建立连接。

2022-01-07 11:05 UTC, sunxyw commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +    public function send($data): bool
这里命名和原本不同，会造成混淆吗
比如测试例中：
```php
go(function () {
    $client = \OneBot\V12\Driver\Swoole\WebSocketClient::createFromAddress('ws://127.0.0.1:9502');
    $client->setMessageCallback(function ($frame, $client) {
        echo "received message: {$frame->data}\n";
        sleep(2);
        $client->push(json_encode(['hello', 'server'])); // 此处
    });
    $client->setCloseCallback(function () {
        echo "Closed\n";
    });
    $client->connect();
    sleep(2);
    $client->send('hello'); // 此处
});
\Swoole\Event::wait();
```

这会对用户造成混乱吗，是不是统一命名会比较好一点，还是说是故意如此以便区分原生与封装的 Client 🤔

2022-01-07 11:09 UTC, crazywhalecc commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +        if (!$this->status != self::STATUS_INITIAL) {
已修复，是测试时改写遗留的

2022-01-07 11:13 UTC, crazywhalecc commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +    public function send($data): bool
Swoole 和 Workerman 的发送函数不一样，Swoole 采用的是 `Server->push($data)`，同时支持二进制数据的 Frame 对象。但 Workerman 的发送为 `$conn->send($data)`，经翻阅文档发现它不能很好地直接支持二进制数据发送（或许可以根据继承对象来实现）。

目前的内容为大体的主要功能实现，为了不产生歧义，`send()` 接口规定为 `push()` 或 `send()` 其实都可以（因为要实现统一的两个驱动，就需要抽象一个接口）。

2022-01-07 11:15 UTC, crazywhalecc commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +    public function send($data): bool
上方测试用例回调内的参数我打算采用一个统一的规定再封装一层，保证 `WebSocketClient` 接口层在两个驱动层面是一致的。但目前改动和新增的内容较多，打算放入后续计划优化。

2022-01-07 11:23 UTC, crazywhalecc commented
后续打算加入一个 EventDispatcher，统一管理所有驱动的 onXXXEvent，包括客户端。

2022-01-07 11:28 UTC, crazywhalecc commented on src/OneBot/V12/Driver/Swoole/WebSocketClient.php
> +    public function send($data): bool
或者 `我全都要`，给两个接口 :smile:

2022-01-07 11:29 UTC, crazywhalecc reviewed
Fixed push/send issue，但是我好像对 Request Changes 有点懵 😢

2022-01-07 11:42 UTC, sunxyw approved these changes

2022-01-07 14:31 UTC, merged