[WIP] 重构配置模块
botuniverse/php-libonebot pull request #69
Opened 2022-09-18 20:26 UTC by sunxyw

2022-09-21 11:03 UTC, crazywhalecc requested changes

2022-09-21 11:03 UTC, crazywhalecc commented on tests/OneBot/Config/ConfigTest.php
> +    private function providerTestConstruct(): array
这里是不是有问题

2022-09-21 11:10 UTC, sunxyw commented on tests/OneBot/Config/ConfigTest.php
> +    private function providerTestConstruct(): array
要用 `public`，我睡醒再修 :smile:

2022-09-22 10:48 UTC, crazywhalecc requested changes
貌似还有问题:(

2022-09-22 12:46 UTC, crazywhalecc approved these changes

2022-09-22 13:21 UTC, merged